#!/bin/bash

# $Id: setup-debian-X11,v 1.7 2001/12/06 18:36:05 freesource Exp $
# make_debian-X11 replacement

# This is usually enough for a minimalistic system
dpkg-reconfigure xfree86-common
dpkg-reconfigure xserver-common
dpkg-reconfigure xfonts-base
dpkg-reconfigure make-debian-x11

# You will want doc/info/man installed, and you may have to make a few
# directories and add a few files.
#dpkg-reconfigure --all

chown -v -R user:user /home/user
chmod 1777 /tmp

# swim --initdb

# Generally a good idea since user-mode-linux doesn't run within itself.
#rm /usr/bin/uml_*
#rm /usr/bin/linux

/etc/cron.daily/find

