#!/bin/bash

# $Id: setup-debian-X11,v 1.8 2001/12/16 09:57:02 freesource Exp $
# make_debian-X11 replacement

# This is usually enough for a minimalistic system
dpkg-reconfigure xfree86-common
dpkg-reconfigure xserver-common
dpkg-reconfigure xfonts-base
dpkg-reconfigure make-debian-x11

# You will want doc/info/man installed, and you may have to make a few
# directories and add a few files.
#dpkg-reconfigure --all

chown -v -R user:user /home/user
chmod 1777 /tmp
chmod 1777 /var/tmp

/etc/cron.daily/find

