
all: install

install:
	install -d $(DESTDIR)/usr/bin
	cp -fa make_debian-X11 $(DESTDIR)/usr/bin/make_debian-X11 
	install -d $(DESTDIR)/usr/share/gbootroot/yard/Replacements
	cp -fa replacements/* $(DESTDIR)/usr/share/gbootroot/yard/Replacements




