
all: install

install:
	install -d /usr/bin
	cp -fa make_debian-X11 /usr/bin/make_debian-X11 
	install -d /usr/share/gbootroot/yard/Replacements
	cp -fa replacements/* /usr/share/gbootroot/yard/Replacements




